name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          cd dapp && forge --version

      - name: Run Forge fmt
        run: |
          cd dapp && forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          cd dapp && forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd dapp && forge test -vvv
        id: test
